### ISSUE TITLE
Use human-readable YAML with bot automerge addition

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#688]
Recently bot automerge was enabled on this feedstock via PR: https://github.com/conda-forge/mapclassify-feedstock/pull/33

Originally the `conda-forge.yml` looked like this

```yaml
conda_forge_output_validation: true
bot:
  automerge: false
  inspection: update-grayskull
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
```

After adding bot automerge it looked like this

```yaml
bot: {automerge: true, inspection: update-grayskull}
conda_build: {pkg_format: '2'}
conda_forge_output_validation: true
github: {branch_name: main, tooling_branch_name: main}
```

Most updates to `conda-forge.yml` use the former YAML syntax, which is much more readable (even though the latter is technically also valid)

Though automerge addition by the bot is an anomaly in this regard. Am curious what we need to do to update the automerge additions to look more like the former (than the latter)
